import React from "react";
import Head from "next/head";
import Navbar from "../navbar/navbar";
import NavbarPrivate from "../navbar/navPrivate/NavPrivate";
import Footer from "../misc/footer";
import pathname from "../misc/pathname";
const Layout = ({ children, signup }: any) => {
  return (
    <div className="mx-auto min-h-screen">
      <Head>
        <title>Greenfie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-white shadow-md ">
        {pathname() === "/" ? <Navbar signup={signup} /> : <NavbarPrivate />}
      </header>
      <main
        className={`container w-full lg:w-5/6 xl:w-5/6 mx-auto mt-20 ${
          pathname() !== "/"
            ? "md:float-right lg:float-right xl:float-right"
            : ""
        }`}
        style={{ marginTop: pathname() === "/" ? "3rem" : "5rem" }}
      >
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
