import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HomePage from "@/components/home";
import Hero from "@/components/hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Greenfie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container h-full mx-auto">
        <section className="md:min-h-[120px]">
        <h1 className="text-main my-8 text-[1.2rem] px-4">Welcome to Greenfie</h1>
        </section>
        <div className="flex flex-wrap justify-center md:justify-between lg:justify-between items-center gap-4">
          <Hero />
          <HomePage />
        </div>

      </main>
    </>
  );
}
