import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Greenfie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container h-full mx-auto">
        <h1 className="text-main mt-10 mb-6 text-[1.2rem] px-4">Welcome to Greenfie</h1>
        <section className="bg-light-background p-6 h-96">
          <h2 className="font-bold p-4 py-5">Our dreams</h2>
          <p className="text-txt">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi
            accusantium veniam voluptates eligendi quas, ab provident voluptatum
            libero a consequuntur.
          </p>
        </section>
        
      </main>
    </>
  );
}
